title: "Program Studi Broadband Multimedia"
description: Website pendukung Akreditasi LAM Teknik.
baseurl: "/aksi-psbm2026"
url: "https://awagyanaKSLF.github.io"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  standar:
    output: true
    permalink: /standar/:path/

defaults:
  - scope:
      path: ""
    values:
      layout: default
